### PR TITLE
Add use MonetaryAmountV2

### PR DESCRIPTION
**Pull request by johantjellden**

### CODE REVIEW

**Comment by palmenhq** [comment]
I believe this will break existing thins in HOPE, we should not remove the `MonetaryAmount` scalar until we've removed all usages

**Comment by johantjellden** [comment]
We are not removing MonetaryAmount from the other schemas. Only from this schema where it is not in use. My reasoning is that during stitching we will not break the other schemas by not having it defined since we are not using it.

**Comment by palmenhq** [comment]
@johantjellden but if we remove the scalar parser we cant parse it anymore?

**Comment by johantjellden** [comment]
Yes but lets not send any MonetaryAmount to this service. When we need to integrate hedgehog cant it send monetaryamountv2 to this service?

**Comment by palmenhq** [comment]
@johantjellden i think it’ll be very confusing but sure. Are we stitching in back-office tho?

**Pull request merged**
